# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'anapencere.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 614)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.baslik_label = QtWidgets.QLabel(self.centralwidget)
        self.baslik_label.setGeometry(QtCore.QRect(140, 40, 491, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(17)
        self.baslik_label.setFont(font)
        self.baslik_label.setAlignment(QtCore.Qt.AlignCenter)
        self.baslik_label.setObjectName("baslik_label")
        self.arama_yap_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.arama_yap_line_edit.setGeometry(QtCore.QRect(30, 170, 751, 20))
        self.arama_yap_line_edit.setObjectName("arama_yap_line_edit")
        self.bilgi_tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.bilgi_tableWidget.setGeometry(QtCore.QRect(30, 230, 741, 281))
        self.bilgi_tableWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bilgi_tableWidget.setShowGrid(False)
        self.bilgi_tableWidget.setObjectName("bilgi_tableWidget")
        self.bilgi_tableWidget.setColumnCount(6)
        self.bilgi_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.bilgi_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.bilgi_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.bilgi_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.bilgi_tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.bilgi_tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.bilgi_tableWidget.setHorizontalHeaderItem(5, item)
        self.bilgi_tableWidget.horizontalHeader().setDefaultSectionSize(120)
        self.bilgi_tableWidget.horizontalHeader().setStretchLastSection(True)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuSe_enekler = QtWidgets.QMenu(self.menubar)
        self.menuSe_enekler.setObjectName("menuSe_enekler")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.bilet_satin_al_sayfa = QtWidgets.QAction(MainWindow)
        self.bilet_satin_al_sayfa.setObjectName("bilet_satin_al_sayfa")
        self.etkinlik_duzenle_sayfa = QtWidgets.QAction(MainWindow)
        self.etkinlik_duzenle_sayfa.setObjectName("etkinlik_duzenle_sayfa")
        self.satilan_biletler_sayfa = QtWidgets.QAction(MainWindow)
        self.satilan_biletler_sayfa.setObjectName("satilan_biletler_sayfa")
        self.menuSe_enekler.addAction(self.bilet_satin_al_sayfa)
        self.menuSe_enekler.addAction(self.etkinlik_duzenle_sayfa)
        self.menuSe_enekler.addAction(self.satilan_biletler_sayfa)
        self.menubar.addAction(self.menuSe_enekler.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.baslik_label.setText(_translate("MainWindow", " Etkinlik ve Bilet Satış Platformu"))
        item = self.bilgi_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.bilgi_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Etkinlik Adı"))
        item = self.bilgi_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Mekan"))
        item = self.bilgi_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Bilet Sayısı"))
        item = self.bilgi_tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Bilet Fiyatı"))
        item = self.bilgi_tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Tarih"))
        self.menuSe_enekler.setTitle(_translate("MainWindow", "Seçenekler"))
        self.bilet_satin_al_sayfa.setText(_translate("MainWindow", "Bilet Satın Al"))
        self.etkinlik_duzenle_sayfa.setText(_translate("MainWindow", "Etkinlik Düzenle"))
        self.satilan_biletler_sayfa.setText(_translate("MainWindow", "Satılan Biletler"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
