# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bilet_satin_al.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(696, 435)
        self.satin_al_buton = QtWidgets.QPushButton(Form)
        self.satin_al_buton.setGeometry(QtCore.QRect(260, 340, 151, 61))
        self.satin_al_buton.setObjectName("satin_al_buton")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(200, 10, 291, 321))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(10, 10, 261, 271))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.id_label = QtWidgets.QLabel(self.widget)
        self.id_label.setObjectName("id_label")
        self.gridLayout.addWidget(self.id_label, 0, 0, 1, 1)
        self.id_line_edit = QtWidgets.QLineEdit(self.widget)
        self.id_line_edit.setObjectName("id_line_edit")
        self.gridLayout.addWidget(self.id_line_edit, 0, 1, 1, 3)
        self.etkinlik_adi_label = QtWidgets.QLabel(self.widget)
        self.etkinlik_adi_label.setObjectName("etkinlik_adi_label")
        self.gridLayout.addWidget(self.etkinlik_adi_label, 1, 0, 1, 1)
        self.etknilik_adi_line_edit = QtWidgets.QLineEdit(self.widget)
        self.etknilik_adi_line_edit.setObjectName("etknilik_adi_line_edit")
        self.gridLayout.addWidget(self.etknilik_adi_line_edit, 1, 2, 1, 2)
        self.isim_label = QtWidgets.QLabel(self.widget)
        self.isim_label.setObjectName("isim_label")
        self.gridLayout.addWidget(self.isim_label, 2, 0, 1, 2)
        self.isim_line_edit = QtWidgets.QLineEdit(self.widget)
        self.isim_line_edit.setObjectName("isim_line_edit")
        self.gridLayout.addWidget(self.isim_line_edit, 2, 2, 1, 2)
        self.bilet_sayisi_label = QtWidgets.QLabel(self.widget)
        self.bilet_sayisi_label.setObjectName("bilet_sayisi_label")
        self.gridLayout.addWidget(self.bilet_sayisi_label, 3, 0, 1, 3)
        self.bilet_sayisi_line_edit = QtWidgets.QLineEdit(self.widget)
        self.bilet_sayisi_line_edit.setObjectName("bilet_sayisi_line_edit")
        self.gridLayout.addWidget(self.bilet_sayisi_line_edit, 3, 3, 1, 1)
        self.odenecek_tutar_label = QtWidgets.QLabel(self.widget)
        self.odenecek_tutar_label.setObjectName("odenecek_tutar_label")
        self.gridLayout.addWidget(self.odenecek_tutar_label, 4, 0, 1, 3)
        self.odenecek_tutar_line_edit = QtWidgets.QLineEdit(self.widget)
        self.odenecek_tutar_line_edit.setObjectName("odenecek_tutar_line_edit")
        self.gridLayout.addWidget(self.odenecek_tutar_line_edit, 4, 3, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.satin_al_buton.setText(_translate("Form", "Satın Al"))
        self.id_label.setText(_translate("Form", "<html><head/><body><p align=\"center\">ID</p></body></html>"))
        self.etkinlik_adi_label.setText(_translate("Form", "<html><head/><body><p align=\"center\">Etkinlik Adı</p></body></html>"))
        self.isim_label.setText(_translate("Form", "Adınız"))
        self.bilet_sayisi_label.setText(_translate("Form", "Bilet Sayısı"))
        self.odenecek_tutar_label.setText(_translate("Form", "Ödenecek Tutar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
